### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ParkSangSun1** [thsamajiki/SeoultechRecipe#1]
= 아래 코드 리뷰는 제 개인적인 생각이니 참고만 해주세요! =
- binding을 사용하는데 findviewbyid를 사용하는 부분이 있습니다https://github.com/thsamajiki/SeoultechRecipe/blob/2177e7252624ada1f4b055fec004bc26645bb306/app/src/main/java/com/seoultech/recipeschoolproject/view/main/recipe/RatingDialog.java#L48
- MVC 패턴이 잘 적용되어 있습니다, Activity or Fragment에서 control 역할과 view역할을 해주고 있는 형태입니다
- listener 패키지에 있는 각각의 interface 파일들을 공통되는 부분은 하나의 파일에 여러 interface를 선언해 주는게 좀 더 깔끔해 보일것 같습니다
- 추가로 코드와는 관련 없지만 리드미에 gif를 직접 녹화하셔서 올리신것 같은데 안드로이드 스튜디오에 에뮬레이터 실행 앱 화면 녹화 기능이 있습니다 👍  (logcat -> 왼쪽 바에서 녹화 아이콘)

**Comment by thsamajiki** [comment]
문제가 되는 부분이 무엇인지에 대해서 다시 한 번 알 수 있게 되었습니다!

유익한 리뷰 감사합니다 :)

**Comment by ParkSangSun1** [comment]
간단한 예제 코드라서 크게 리뷰할 것은 많이 없는 것 같습니다! 코틀린으로 마이그레이션 진행하고 계시는 것 같던데 파이팅입니다!

**Comment by thsamajiki** [comment]
감사합니다.
이 정도 스케일의 프로젝트는 1인 개발 토이 프로젝트 수준이라 생각하시고, 또 네카라에 서류 지원하는데 어필하기에 부족하다고 생각하시나요?
UI를 좀더 세련되게 디자인하면 좀더 나을수도 있겠지만, 그냥 하얀 바탕의 검정색 폰트와 purple 컬러(primaryColor)를 몇군데 추가한 정도인데, 네카라쿠배 서류 지원하는데에는 많이 부족할까요?

(코드를 실행해보셨는지까지는 잘 모르겠습니다만, 모르셔도 알 수 있다면 굳이 실행을 안해도 상관은 없을거 같습니다 ^^;)

**Comment by ParkSangSun1** [comment]
제 개인적인 생각으로 냉정하게 봤을 때 네카라쿠배 서류에 지원하기에는 많이 부족해 보입니다..
앱 아이디어 자체가 너무 식상한 토이 프로젝트이기 때문에 조금 더 사용자 관점에서 생각해 보시고 독특한 앱을 만들어 직접 서비스해 보는 경험을 더 높은 점수를 줄 거라 생각됩니다
또 요즘 광고에서 네카라배 취업 가능하다 이런 광고들을 많이 돌아다녀 쉬울 것 같지만 생각보다 허들이 높고 또 프로젝트도 프로젝트지만 코딩 테스트 알고리즘 또한 큰 비중을 차지합니다;;

저도 가본 적은 없어서 자세히는 모르지만 응원하겠습니다!

**Comment by thsamajiki** [comment]
(가본 적 없다고 하셨지만 그래도 궁금해서 질문드립니다)
근데 신입 공채 코테 통과하면 괜찮지 않을까요?

신입한테 얼마나 대단한 걸 바라겠냐고 얘기하는 사람들도 있어서 이정도도 괜찮지 않나하는 생각도 들었는데,
(독특한 앱을 만들어 직접 서비스해본 경험까지 요구한다면 창업을 하는 것이 맞지 않냐고 얘기하는 사람들이
다른 안드로이드 오픈채팅방에 있었습니다.)
누구 말이 맞는 것인지 몰라서 질문드립니다.

 (현재 신입 취준생입니다)

**Comment by thsamajiki** [comment]
코틀린으로 마이그레이션 진행하고 있는데, 마이그레이션과 리팩토링 경험을 어필하는 것은 Advantage가 될지, 어떻게 생각하시는지 답 주시면 감사하겠습니다!

**Comment by ParkSangSun1** [comment]
제 개인적인 생각으로는 갈수록 신입에게 바라는 요구 허들이 높아지고 있다고 생각합니다
또 지금 채용 시장은 신입에게는 최악이라고 생각됩니다
스타트업들은 투자 받기가 힘들어져 채용을 하지 않고 대기업들도 사리고 있는 것 같고요.
그럼 당연히 대기업 신입 공채에 다 모여들 텐데 경쟁률이 더 높아질 겁니다
여기서 직접 서비스한 경험은 물론 반드시 있어야 하는 건 아니겠지만 분명 플러스 점수로 먹히는 건 분명하다고 생각됩니다
물론 반드시 있어야 하는 건 아니지만 자신의 경쟁력을 높이려면 최대한 많은 것을 해보고 경험해 보는 게 좋겠죠

제 기억으로는 대기업 신입 공채에도 1차나 코테 다음 포폴이나 이력서가 포함되는 걸로 알고 있습니다
그래서 코테 + 포폴 두 마리 토끼 모두 잡아야 합니다
그나마 좋은 소식은 채용 과정에서 코테가 점점 사라지고 과제 전형으로 대체되는 추세입니다

**Comment by ParkSangSun1** [comment]
코틀린으로 마이그레이션 경험과 리팩토링 경험 당연히 플러스입니다
MVC에서 MVVM으로 디자인 패턴도 적용해 보시면 많이 도움도 될 거고 포폴에 한 줄 더 쓸 수 있겠죠

면접 질문에서 코드를 더 효율적으로 그리고 클린 하게 짜기 위해 고민해 보고 직접 해본 경험이 있냐 이런 질문도 나옵니다

**Comment by thsamajiki** [comment]
네 알겠습니다.
주변에 인맥이 워낙 없다보니 질문을 많이 하게 되네요.
개인 오픈채팅방 만들어서 질문드려도 될까요?
(근데 민폐일거 같아서ㅜㅜ)
(어려우시면) 생각날 때 단톡방에서 여러 톡방 분들한테도 질문을 하겠습니다.

**Comment by ParkSangSun1** [comment]
개인 오픈 채팅방으로 질문해 주셔도 괜찮습니다, 아는 선에서는 답변드리겠습니다!
이슈는 이제 닫겠습니다, 좋은 밤 되세요 :)
